version: "3.8"

services:
  api:
    build: ../backend/media
    container_name: mesh_api
    environment:
      API_PORT: "8080"
      NETWORK_HOST: node1
      NETWORK_PORT: "9001"
      USE_MOCK: "false"
    ports:
      - "8080:8080"
    networks:
      - mesh
    restart: on-failure

networks:
  mesh:
    driver: bridge
